package ::classPack::;
import parseSpod.parse.*;
import parseSpod.parse.ParseObjectHelper;
import promhx.Promise;

/**
 * Generated by Parse Spod Tool (v::toolVersion::)
 */
@:access(parseSpod.parse.ParseFile)
abstract ::className::(String)
{
	static var loadedObjects:Map<String, Bool> = new Map();
	
	::foreach fields::
	static var ::safeName::_local:Map<String, ::type::> = new Map();
	static var ::safeName::_remote:Map<String, ::type::> = new Map();
    ::end::
	
	::foreach pointers::
	static var ::safeName::_local:Map<String, ::type::> = new Map();
	static var ::safeName::_remote:Map<String, ::type::> = new Map();
    ::end::
	
	::foreach files::
	static var ::safeName::_local:Map<String, ::type::> = new Map();
	static var ::safeName::_remote:Map<String, ::type::> = new Map();
    ::end::
	
	::foreach relations::
	static var ::safeName::_local:Map<String, Array<::type::>> = new Map();
	static var ::safeName::_remote:Map<String, Array<::type::>> = new Map();
	static var ::safeName::_added:Map<String, Array<::type::>> = new Map();
	static var ::safeName::_removed:Map<String, Array<::type::>> = new Map();
	static var ::safeName::_loaded:Map<String, Bool> = new Map();
    ::end::
	
	static function getDesc() : EntityDesc
	{
		return desc;
	}
	
	static var desc:EntityDesc = {
		loaded:loadedObjects,
		coerceData:get,
		fields:[
	
	::foreach fields::
			{name:"::safeName::", local:::safeName::_local, remote:::safeName::_remote, type:::descType::},::end::
	::foreach files::
			{name:"::safeName::", local:::safeName::_local, remote:::safeName::_remote, type:::descType::},::end::
	::foreach pointers::
			{name:"::safeName::", local:::safeName::_local, remote:::safeName::_remote, type:::descType::, remoteType:::remoteType::, entityDesc:ParseDescReg.get.bind("::classPack::.::type::")},::end::
	::foreach relations::
			{name:"::safeName::", local:::safeName::_local, remote:::safeName::_remote, added:::safeName::_added, removed:::safeName::_removed, type:::descType::, remoteType:::remoteType::, entityDesc:ParseDescReg.get.bind("::classPack::.::type::")},::end::
    
	
		]};
	
	inline public static function all() : Promise<Array<::className::>> {
		Server.setup();
		return ParseObjectHelper.query("::appName::", "::remoteClassName::", desc);
	}
	
	inline public static function query() : ParseQuery<::className::> {
		Server.setup();
		return new ParseQuery("::appName::", "::remoteClassName::", desc);
	}
	
	inline public static function create() : ::className:: {
		Server.setup();
		return new ::className::(ParseObjectId.getLocal());
	}
	
	inline public static function get(id:String) : ::className:: {
		Server.setup();
		return new ::className::(id);
	}
	
	
	public var objectId(get, never):String;
	inline function get_objectId():String {
		return this;
	}
	
	public var loaded(get, never):Bool;
	inline function get_loaded():Bool {
		return ParseObjectHelper.getLoaded(this, loadedObjects);
	}
	
	public var saved(get, never):Bool;
	inline function get_saved():Bool {
		return ParseObjectId.isLocal(objectId);
	}
	
	public var hasChanges(get, never):Bool;
	inline function get_hasChanges():Bool {
		return ParseObjectHelper.hasChanges(objectId, desc);
	}
	
	::foreach fields::
	public var ::safeName::(get, set):::type::;
	inline function get_::safeName::():::type:: {
		return ParseObjectHelper.get(objectId, ::safeName::_local, ::safeName::_remote);
	}
	inline function set_::safeName::(value:::type::):::type:: {
		return ParseObjectHelper.set(objectId, value, ::safeName::_local, ::safeName::_remote);
	}
	::end::
	
	::foreach files::
	public var ::safeName::(get, set):::type::;
	inline function get_::safeName::():::type:: {
		return ParseObjectHelper.get(objectId, ::safeName::_local, ::safeName::_remote);
	}
	inline function set_::safeName::(value:::type::):::type:: {
		return ParseObjectHelper.set(objectId, value, ::safeName::_local, ::safeName::_remote);
	}
	inline public function ::safeName::Upload(saveEntity:Bool=false):Promise<ParseFile> {
		return ::safeName::.uploadForEntity("::appName::", objectId, ::safeName::_local, saveEntity ? ParseObjectHelper.save.bind(objectId, this, "::appName::", "::remoteClassName::", desc, ["::safeName::"]) : null );
	}
	::end::
	
	::foreach pointers::
	public var ::safeName::(get, set):::type::;
	inline function get_::safeName::():::type:: {
		return ParseObjectHelper.get(objectId, ::safeName::_local, ::safeName::_remote);
	}
	inline function set_::safeName::(value:::type::):::type:: {
		return ParseObjectHelper.set(objectId, value, ::safeName::_local, ::safeName::_remote);
	}
	::end::
	
	
	
	::foreach relations::
	public var ::safeName::(get, never):Array<::type::>;
	inline function get_::safeName::():Array<::type::> {
		return ParseRelationHelper.get(this, ::safeName::_local);
	}
	inline public function ::safeName::Load(overwriteChanges:Bool=false):Promise<Array<::type::>> {
		return ParseRelationHelper.load("::appName::", "::remoteClassName::", this, ::remoteType::, "::safeName::", ::safeName::_local, ::safeName::_added, ::safeName::_removed, ::safeName::_remote, ::safeName::_loaded, overwriteChanges, ParseDescReg.get("::classPack::.::type::"));
	}
	inline public function ::safeName::Save():Promise<Array<::type::>> {
		return ParseRelationHelper.save("::appName::", "::remoteClassName::", this, ::remoteType::, "::safeName::", ::safeName::_local, ::safeName::_added, ::safeName::_removed, ::safeName::_remote);
	}
	inline public function ::safeName::Add(entity:::type::):Void {
		ParseRelationHelper.add(this, ::safeName::_local, ::safeName::_added, ::safeName::_removed, entity);
	}
	inline public function ::safeName::Remove(entity:::type::):Void {
		ParseRelationHelper.remove(this, ::safeName::_local, ::safeName::_added, ::safeName::_removed, ::safeName::_loaded, entity);
	}
	inline public function ::safeName::Loaded():Bool {
		return ParseRelationHelper.loaded(this, ::safeName::_loaded);
	}
	::end::

	private function new(objectId:String) 
	{
		Server.setup();
		this = objectId;
	}
	
	
	inline public function save() : Promise<::className::>
	{
		return untyped ParseObjectHelper.save(objectId, this, "::appName::", "::remoteClassName::", desc);
	}
	inline public function load(overwriteChanges:Bool=false) : Promise<::className::>
	{
		return untyped ParseObjectHelper.load(objectId, this, overwriteChanges, "::appName::", "::remoteClassName::", desc);
	}
	inline public function delete() : Promise<::className::>
	{
		return untyped ParseObjectHelper.delete(objectId, this, "::appName::", "::remoteClassName::", desc);
	}
	public function revert() : Bool
	{
		return ParseObjectHelper.revert(objectId, desc);
	}
	
	inline public function toString() : String
	{
		return ParseObjectHelper.toString(objectId, desc);
	}
	
}