package ::classPack::;
import haar.*;
import promhx.Promise;
import parse.*;
import haar.ParseObjectHelper;

/**
 * Generated by Haar Tool (v::haarVersion::)
 */
::foreach relations::
@:access(::classPack::.::type::)::end::
abstract ::className::(String)
{
	static var loadedObjects:Map<String, Bool> = new Map();
	
	::foreach fields::
	static var ::name::_local:Map<String, ::type::> = new Map();
	static var ::name::_remote:Map<String, ::type::> = new Map();
    ::end::
	
	::foreach relations::
	static var ::name::_local:Map<String, Array<::type::>> = new Map();
	static var ::name::_remote:Map<String, Array<::type::>> = new Map();
	static var ::name::_added:Map<String, Array<::type::>> = new Map();
	static var ::name::_removed:Map<String, Array<::type::>> = new Map();
	static var ::name::_loaded:Map<String, Bool> = new Map();
    ::end::
	
	static var desc:EntityDesc = {loaded:loadedObjects,
		fields:[
	
	::foreach fields::
			{name:"::name::", local:::name::_local, remote:::name::_remote, type:::descType::, remoteType:::remoteType::},::end::
	
	::foreach relations::
			{name:"::name::", local:::name::_local, remote:::name::_remote, added:::name::_added, removed:::name::_removed, type:::descType::, remoteType:::remoteType::},::end::
    
	
		]};
	
	inline public static function all() : Promise<Array<::className::>> {
		return ParseObjectHelper.query("::serverId::", "::remoteClassName::", desc);
	}
	
	inline public static function query() : ParseQuery<App> {
		return new ParseQuery("::serverId::", "::remoteClassName::", desc);
	}
	
	inline public static function create() : ::className:: {
		return new ::className::(ParseObjectId.getLocal());
	}
	
	
	public var objectId(get, never):String;
	inline function get_objectId():String {
		return this;
	}
	
	public var loaded(get, never):Bool;
	inline function get_loaded():Bool {
		return ParseObjectHelper.getLoaded(this, loadedObjects);
	}
	
	public var saved(get, never):Bool;
	inline function get_saved():Bool {
		return ParseObjectId.isLocal(objectId);
	}
	
	::foreach fields::
	public var ::name::(get, set):::type::;
	inline function get_::name::():::type:: {
		return ParseObjectHelper.get(objectId, ::name::_local, ::name::_remote);
	}
	inline function set_::name::(value:::type::):::type:: {
		return ParseObjectHelper.set(objectId, value, ::name::_local, ::name::_remote);
	}
	::end::
	
	
	
	::foreach relations::
	public var ::name::(get, never):Array<::type::>;
	inline function get_::name::():Array<::type::> {
		return ParseRelationHelper.get(this, ::name::_local);
	}
	inline public function ::name::Load(overwriteChanges:Bool=false):Promise<Array<::type::>> {
		return ParseRelationHelper.load("::serverId::", "::remoteClassName::", this, ::remoteType::, "::name::", ::name::_local, ::name::_added, ::name::_removed, ::name::_remote, ::name::_loaded, overwriteChanges, ::type::.desc);
	}
	inline public function ::name::Save():Promise<Array<::type::>> {
		return ParseRelationHelper.save("::serverId::", "::remoteClassName::", this, ::remoteType::, "::name::", ::name::_local, ::name::_added, ::name::_removed, ::name::_remote);
	}
	inline public function ::name::Add(tag:::type::):Void {
		ParseRelationHelper.add(this, ::name::_local, ::name::_added, ::name::_removed, tag);
	}
	inline public function ::name::Remove(tag:::type::):Void {
		ParseRelationHelper.remove(this, ::name::_local, ::name::_added, ::name::_removed, ::name::_loaded, tag);
	}
	inline public function ::name::Loaded():Bool {
		return ParseRelationHelper.loaded(this, ::name::_loaded);
	}
	::end::

	private function new(objectId:String) 
	{
		this = objectId;
	}
	
	
	inline public function save() : Promise<::className::>
	{
		return untyped ParseObjectHelper.save(objectId, this, "::serverId::", "::remoteClassName::", desc);
	}
	inline public function load(overwriteChanges:Bool=false) : Promise<::className::>
	{
		return untyped ParseObjectHelper.load(objectId, this, overwriteChanges, "::serverId::", "::remoteClassName::", desc);
	}
	inline public function delete() : Promise<::className::>
	{
		return untyped ParseObjectHelper.delete(objectId, this, "::serverId::", "::remoteClassName::", desc);
	}
	
	inline public function toString() : String
	{
		return ParseObjectHelper.toString(objectId, desc);
	}
	
}