package ::classPack::;
import haar.ParseIO;
import haar.ParseServerHelper;
import haar.ParseUrls;
import haar.http.Http.HttpMethod;
import promhx.Promise;

/**
 * Generated by Haar Tool (v::haarVersion::)
 */
class ::className::
{

	public function new() 
	{
		
	}
	
	public static function setToken(token:String) : Void
	{
		ParseIO.setToken("::serverId::", token);
	}
	
	public static function getSession(token:String, useToken:Bool=true) 
	{
		return ParseServerHelper.getSession("::serverId::", token, useToken);
	}
	
	public static function signup(signupOptions:SignupOptions, useToken:Bool=true) : Promise<Session>
	{
		return ParseServerHelper.signup("::serverId::", signupOptions, useToken);
	}
	public static function signin(username:String, password:String, useToken:Bool=true) : Promise<Session>
	{
		return ParseServerHelper.signin("::serverId::", username, password, useToken);
	}
	public static function passwordReset(email:String) : Promise<Bool>
	{
		return ParseServerHelper.passwordReset("::serverId::", email);
	}
	public static function signout() : Void
	{
		setToken(null);
	}
}